language: python
#Set the language and turn off email
email: false

#Slack notifications!
#we always want notifications if build fails
#we only want success notifications if change
notifications:
  slack: $slack_key
    on_success: change
    on_failure: always


#compile all python files
script:
  - python -m py_compile attendance-website/autoLogout.py
  - python -m py_compile attendance-website/manage.py
  - python -m py_compile attendance-website/attendance/urls.py
  - python -m py_compile attendance-website/attendance/wsgi.py
  - python -m py_compile attendance-website/attendance/settings.py
  - python -m py_compile attendance-website/attendanceapp/admin.py
  - python -m py_compile attendance-website/attendanceapp/models.py
  - python -m py_compile attendance-website/attendanceapp/tests.py
  - python -m py_compile attendance-website/attendanceapp/views.py
